project:
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Project"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: "Reports"
        contents:
          - href: report1.qmd
          - href: report2.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true